[tool.poetry]
name = "bucica-api"
version = "0.1.0"
description = ""
authors = ["Einstein Floripa <vale@einsteinfloripa.com.br>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.92.0"
sqlalchemy = "^2.0.4"
uvicorn = "^0.20.0"
pydantic = "^1.10.5"
psycopg2 = "^2.9.5"
pytest-mock = "^3.10.0"
mock = "^5.0.1"
python-dotenv = "^1.0.0"
faker = "^18.3.1"

[tool.poetry.group.dev.dependencies]
pylint = "^2.16.2"
black = "^23.1.0"
mypy = "^1.0.1"
alembic = "^1.9.4"
pytest = "^7.2.1"
pre-commit = "^3.2.1"

[tool.black]
line-length = 100
exclude = '''
(
  /(
      \.git
    | \.venv
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.vscode
    | _build
    | buck-out
    | build
    | dist
    | alembic
  )/
)
'''

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
