"""change 'criado_em' to date

Revision ID: 0c3b7d8a51ab
Revises: 1bc8eeaf063c
Create Date: 2023-03-19 09:22:00.901002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3b7d8a51ab'
down_revision = '1bc8eeaf063c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Presenca', 'criado_em',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Presenca', 'criado_em',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
