"""initial database schema

Revision ID: 0fa6e7b2f5e8
Revises:
Create Date: 2023-03-17 19:26:52.018381

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from src.utils.schedule import LateTypes

# revision identifiers, used by Alembic.
revision = "0fa6e7b2f5e8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    late_types = postgresql.ENUM(LateTypes, name="latetypes")
    late_types.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Cadastro_Alunos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("birthdate", sa.Date(), nullable=True),
        sa.Column("rg", sa.String(), nullable=True),
        sa.Column("cpf", sa.String(), nullable=True),
        sa.Column("civil_state", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("neighborhood", sa.String(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("number", sa.String(), nullable=True),
        sa.Column("complement", sa.String(), nullable=True),
        sa.Column("cep", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
    )
    op.create_table(
        "Presenca",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.Column("datetime_of_creation", sa.DateTime(), nullable=True),
        sa.Column("absence", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["student_id"], ["Cadastro_Alunos.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    op.add_column("Presenca", sa.Column("atraso", late_types, nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Presenca")
    op.drop_table("Cadastro_Alunos")
    # ### end Alembic commands ###
