"""change 'criado_em' to date

Revision ID: 1bc8eeaf063c
Revises: c30f103092b2
Create Date: 2023-03-19 09:13:59.239059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bc8eeaf063c'
down_revision = 'c30f103092b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Presenca', 'atraso',
               existing_type=postgresql.ENUM('on_time', 'half_late', 'late', name='latetypes'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Presenca', 'atraso',
               existing_type=postgresql.ENUM('on_time', 'half_late', 'late', name='latetypes'),
               nullable=True)
    # ### end Alembic commands ###
