"""first_table_model

Revision ID: 2d6b10cfcb5d
Revises: 
Create Date: 2023-03-12 22:35:28.390379

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2d6b10cfcb5d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Cadastro_Alunos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("birthdate", sa.Date(), nullable=True),
        sa.Column("rg", sa.String(), nullable=True),
        sa.Column("cpf", sa.String(), nullable=True),
        sa.Column("civil_state", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("neighborhood", sa.String(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("number", sa.String(), nullable=True),
        sa.Column("complement", sa.String(), nullable=True),
        sa.Column("cep", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rg"),
    )
    op.create_index(
        op.f("ix_Cadastro_Alunos_cpf"), "Cadastro_Alunos", ["cpf"], unique=True
    )
    op.create_index(
        op.f("ix_Cadastro_Alunos_name"), "Cadastro_Alunos", ["name"], unique=False
    )
    op.create_table(
        "Presenca",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("studant_id", sa.Integer(), nullable=True),
        sa.Column("datetime", sa.DateTime(), nullable=True),
        sa.Column("late", sa.String(), nullable=True),
        sa.Column("absence", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["studant_id"],
            ["Cadastro_Alunos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Presenca")
    op.drop_index(op.f("ix_Cadastro_Alunos_name"), table_name="Cadastro_Alunos")
    op.drop_index(op.f("ix_Cadastro_Alunos_cpf"), table_name="Cadastro_Alunos")
    op.drop_table("Cadastro_Alunos")
    # ### end Alembic commands ###
