"""remove 'data_nascimento' column

Revision ID: 788a306aab4d
Revises: 6d3a43bff9b1
Create Date: 2023-04-10 20:54:02.616271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '788a306aab4d'
down_revision = '6d3a43bff9b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cadastro_Alunos', 'data_nascimento')
    op.alter_column('Presenca', 'atraso',
               existing_type=postgresql.ENUM('ON_TIME', 'HALF_LATE', 'LATE', name='latetypes'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Presenca', 'atraso',
               existing_type=postgresql.ENUM('ON_TIME', 'HALF_LATE', 'LATE', name='latetypes'),
               nullable=True)
    op.add_column('Cadastro_Alunos', sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
