version: '3'

services:
  bucica-api-production:
    container_name: bucica-api-production
    image: bucica-api-production
    env_file:
      - ../../.env.production
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    depends_on:
      - bucica-postgres-db-production
    networks:
      - bucica-network-production
    command: sh -c "poetry run alembic upgrade head && poetry run uvicorn --host 0.0.0.0 --port ${PORT} src.main:app"

  bucica-postgres-db-production:
    container_name: bucica-postgres-db-production
    image: postgres:12.2-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    networks:
      - bucica-network-production

networks:
  bucica-network-production:
    name: bucica-network-production

volumes:
  postgres-data-production:
