name: CD(Deploy to Hostinger Production)

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-production:
    name: Deploy to Hostinger (Production)
    environment:
      name: Production
      url: https://api.einsteinfloripa.com.br
    runs-on: self-hosted
    steps:
      - name: Checkout in branch ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{ vars.PORT }}
          envkey_POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          envkey_POSTGRES_HOST: bucica-postgres-db-production
          envkey_DB_PORT: ${{ vars.DB_PORT }}
          envkey_DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
          envkey_ADMIN_USERNAME: ${{ vars.ADMIN_USERNAME }}
          envkey_ADMIN_PASSWORD: ${{ vars.ADMIN_PASSWORD }}
          file_name: .env.production
          fail_on_empty: true

      - name: Deploy to Hostinger
        run: |
          make deploy-production
          make deploy-nginx
