name: CI(Deploy to Hostinger)

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-production:
    if: ${{ github.ref_name == 'main' }}
    name: Deploy to Hostinger (Production)
    environment:
      name: Production
      url: https://api.einsteinfloripa.com.br
    runs-on: self-hosted
    steps:
      - name: Checkout in branch ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{ vars.PORT }}
          envkey_POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          envkey_DB_PORT: ${{ vars.DB_PORT }}
          file_name: .env.staging
          fail_on_empty: true

      - name: Deploy to Hostinger
        run: |
          make deploy-production
          make deploy-nginx

  deploy-staging:
    if: ${{ github.ref_name == 'develop' }}
    name: Deploy to Hostinger (Staging)
    runs-on: self-hosted
    environment:
      name: Staging
      url: https://staging-api.einsteinfloripa.com.br

    steps:
      - name: Checkout in branch ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{ vars.PORT }}
          envkey_POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          envkey_DB_PORT: ${{ vars.DB_PORT }}
          file_name: .env.staging
          fail_on_empty: true

      - name: Deploy to Hostinger
        run: |
          make deploy-staging
          make deploy-nginx
