name: Lint PR

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  main:
    name: Check PR name
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
