name: CI(Tests)

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests-unit:
    name: Unit Tests
    runs-on: ubuntu-22.04
    env:
      DB_URL: "sqlite:///test.db"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: |
          source $VENV
          pytest -m unit

  tests-integration:
    name: Integration Tests
    runs-on: ubuntu-22.04
    env:
      DB_URL: sqlite:///test.db
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: |
          source $VENV
          pytest -m integration
