name: CI(Tests)

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        test_type: [unit, integration]
    env:
      DB_URL: "sqlite:///test.db"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Run ${{ matrix.test_type }} tests
        run: |
          source $VENV
          pytest -m ${{ matrix.test_type }}
